# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: David Diamond
email: hi@daviddiamond.co
description: I’m David, a product designer living in Dublin… Most recently I’ve been designing software at Intercom. Helping internet businesses stay personal at scale working accross Desktop, iOS and Android shipping small tweaks, getting my hands dirty with code and full feature releases. Right now I’m working with clients looking to build really, really well designed software.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://daviddiamond.co" # the base hostname & protocol for your site
gems: [jekyll-admin]



# Build settings
markdown: kramdown
